Dim swApp As Object
Dim swModel As SldWorks.ModelDoc2
Dim swDraw As SldWorks.DrawingDoc
Dim Part As Object

Sub Easy_A_Drawing()

'Set up Solidworks
Set swApp = Application.SldWorks
'Get active document
Set swModel = swApp.ActiveDoc
ModelPath = swModel.GetPathName

'Find the plane with the sketch in


'Get the principle plane
PrinciplePlane = InputBox("What is the main plane the profile is drawn in?" & vbNewLine & vbNewLine & "Front plane = F" & vbNewLine & "Top plane = T" & vbNewLine & "Right plane = R", "Principle Plane")

If PrinciplePlane = "F" Or PrinciplePlane = "f" Then
    MainPlane = "*Front"
ElseIf PrinciplePlane = "T" Or PrinciplePlane = "t" Then
    MainPlane = "*Top"
ElseIf PrinciplePlane = "R" Or PrinciplePlane = "r" Then
    MainPlane = "*Right"
End If

'Get sheet size
SheetSizeInput = InputBox("What sheet size do you need?" & vbNewLine & vbNewLine & "Enter:" & vbNewLine & "  4 for A4" & vbNewLine & "  3 for A3" & vbNewLine & "  2 for A2" & vbNewLine & "  1 for A1", "SHEET SIZE REQUIRED")

Dim swSheetWidth As Double
Dim swSheetHeight As Double
Dim SheetFormatPath As String

If SheetSizeInput = "4" Then
    swSheetWidth = 0.297
    swSheetHeight = 0.21
    SheetFormatPath = "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A4.slddrt"
ElseIf SheetSizeInput = "3" Then
    swSheetWidth = 0.42
    swSheetHeight = 0.297
    SheetFormatPath = "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A3.slddrt"
ElseIf SheetSizeInput = "2" Then
    swSheetWidth = 0.594
    swSheetHeight = 0.42
    SheetFormatPath = "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A2.slddrt"
ElseIf SheetSizeInput = "1" Then
    swSheetWidth = 0.841
    swSheetHeight = 0.594
    SheetFormatPath = "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A1.slddrt"
Else
    'Default to A3
    swSheetWidth = 0.42
    swSheetHeight = 0.297
    SheetFormatPath = "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A3.slddrt"
End If

'Open drawing for part
Set Part = swApp.NewDocument("C:\NPD\Admin\Templates\SolidWorks PDM Templates\A3 SW Rev Table.drwdot", 12, swSheetWidth, swSheetHeight)

'Update sheet format
Part.SetupSheet5 "Sheet1", 12, 12, 1, 1, False, SheetFormatPath, swSheetWidth, swSheetHeight, "Default", True

'Import drawing
Part.GraphicsRedraw2
Dim myView As Object
Set myView = Part.CreateDrawViewFromModelView3(ModelPath, MainPlane, (1.5 * swSheetWidth) / 4, swSheetHeight / 2, 0)
boolstatus = myView.AutoInsertCenterMarks2(7, 11, True, True, True, 0.0025, 0.0025, True, True, 0)
boolstatus = myView.SetDisplayMode3(False, 1, False, True)
'boolstatus = Part.Extension.SelectByID2("Drawing View11", "DRAWINGVIEW", 0, 0, 0, False, 0, Nothing, 0)
'boolstatus = Part.ActivateView("Drawing View11")
Set myView = Part.CreateUnfoldedViewAt3((3 * swSheetWidth) / 4, swSheetHeight / 2, 0, False)


'Dimension the drawing
Dim vAnnotations As Variant
vAnnotations = Part.InsertModelAnnotations3(0, 1212424, True, True, False, False)
'vAnnotations = Part.InsertModelAnnotations3(0, 32768, True, True, False, False)
'vAnnotations = Part.InsertModelAnnotations3(0, 1048576, True, True, False, True)



'Open new sheet and add DXF file
bRet = Part.ActivateSheet("Sheet2")
If bRet Then
    Part.SetupSheet5 "Sheet2", 12, 12, 1, 1, False, SheetFormatPath, swSheetWidth, swSheetHeight, "Default", True
End If
Set myView = Part.CreateDrawViewFromModelView3(ModelPath, MainPlane, swSheetWidth / 2, swSheetHeight / 2, 0)

'Return to first sheet
bRet = Part.ActivateSheet("Sheet1")

    'Add a new note to the sheet format template
    Dim swNote As Note
    'Set Part = swApp.ActiveDoc
    Set swNote = Part.InsertNote("THIS DRAWING HAS BEEN AUTOMATICALLY GENERATED")
    Dim swAnno As Annotation
    Set swAnno = swNote.GetAnnotation
    swAnno.SetPosition2 0.011, 0.27, 0
    Dim txtFormat As TextFormat
    Set txtFormat = swAnno.GetTextFormat(0)
    txtFormat.BackWards = (txtFormat.BackWards = False)
    txtFormat.Bold = True
    txtFormat.CharHeightInPts = 1 * txtFormat.CharHeightInPts
    swAnno.SetTextFormat 0, False, txtFormat

bRet = Part.ForceRebuild3(False)

End Sub


