'NEED TO DECLARE VARIABLES THAT ARE USED IN MULTIPLE SUBS AND SPECIAL SOLIDWORKS OBJECTS
Dim FirstTime As Variant

'Section of code that defines the corners of the table for anchor points
Public Enum swBOMConfigurationAnchorType_e
    swBOMConfigurationAnchor_TopLeft = 1
    swBOMConfigurationAnchor_TopRight = 2
    swBOMConfigurationAnchor_BottomLeft = 3
    swBOMConfigurationAnchor_BottomRight = 4
End Enum

'Deleting values
Dim swTableAnnotation As SldWorks.TableAnnotation
Dim swGeneralTableFeature As SldWorks.GeneralTableFeature
Dim swSelectionMgr As SldWorks.SelectionMgr
Dim swModelDocExt As SldWorks.ModelDocExtension
Dim swFeature As SldWorks.Feature
Dim swAnn As SldWorks.Annotation

'Dim vPics As Variant
Dim swSkPic As SldWorks.SketchPicture
Dim swSketch As SldWorks.Sketch

'Copying Variables
Dim swApp As SldWorks.SldWorks
Dim swModel As SldWorks.ModelDoc2
Dim swmod As SldWorks.ModelDoc2
Dim swDraw As SldWorks.DrawingDoc
Dim swview As SldWorks.View
Dim comp As SldWorks.Component2
Dim swCustPropMgr As SldWorks.CustomPropertyManager
Dim Tolerance_Data(35, 1) As String

Dim swEnt As SldWorks.Entity
Dim swConfigMgr As SldWorks.ConfigurationManager
Dim swConf As SldWorks.Configuration
Dim swComp As SldWorks.Component2
Dim swParentComp As SldWorks.Component2
Dim swRootDrawComp As SldWorks.DrawingComponent

'All variables in the custom properties tab
Dim TolTab As Variant
Dim Watermark As Variant

'Determine Name And Type Variables
Dim DrawType As Integer

'Table Variables
Dim swSelMgr As SldWorks.SelectionMgr
Dim swFeat As SldWorks.Feature
Dim swSheet As SldWorks.Sheet
Dim swTable As SldWorks.TableAnnotation
Dim swTable2 As SldWorks.TableAnnotation
Dim swTable3 As SldWorks.TableAnnotation
Dim swTable4 As SldWorks.TableAnnotation
Dim vPickPt As Variant
Dim vSheetProps As Variant
Dim swTextFormat As SldWorks.TextFormat
Dim swTextFormatTitle As SldWorks.TextFormat
Dim swTextFormatBold As SldWorks.TextFormat
Dim swTextFormatTitleBlock As SldWorks.TextFormat
Dim swTextFormatDWGNo As SldWorks.TextFormat
Dim swTextFormatLeftJust As SldWorks.TextFormat
Dim swTextFormatSheetSize As SldWorks.TextFormat

'Insert BOM Table Variables
Dim swBOMAnnotation         As SldWorks.BomTableAnnotation
Dim swBOMFeature            As SldWorks.BomFeature

'Insert picture variables
Dim SkPicture As Object
Dim SkPicture2 As Object

'Text Box Variable
Dim str As String
Dim CustomProperties(1 To 100)
Dim swNote  As SldWorks.Note
Dim Annotation As SldWorks.Annotation
Dim swTable5 As SldWorks.TableAnnotation
Dim swTextFormatWatermark As SldWorks.TextFormat
Dim swTextFormatNoItalic As SldWorks.TextFormat

'Sheet properties variables
Public Enum swDwgPaperSizes_e
    swDwgPaperAsize = 0
    swDwgPaperAsizeVertical = 1
    swDwgPaperBsize = 2
    swDwgPaperCsize = 3
    swDwgPaperDsize = 4
    swDwgPaperEsize = 5
    swDwgPaperA4size = 6
    swDwgPaperA4sizeVertical = 7
    swDwgPaperA3size = 8
    swDwgPaperA2size = 9
    swDwgPaperA1size = 10
    swDwgPaperA0size = 11
    swDwgPapersUserDefined = 12
End Enum
Dim vSheetNames As Variant

'swCommands Variables
Dim swCommand_Border_Editor As swCommands_e

Public SheetSizeInput As Variant

' -------------------------------------------------------------------------------------------------------------

Sub CreateViewLayout()
'This section creates the standard view layout: top view, side view, and isometric view
    
    Dim swDrawingDoc As SldWorks.DrawingDoc
    Dim swModelDoc As SldWorks.ModelDoc2
    Dim swView1 As SldWorks.View
    Dim swView2 As SldWorks.View
    Dim swView3 As SldWorks.View
    Dim swView4 As SldWorks.View
    Dim sheetWidth As Double
    Dim sheetHeight As Double
    Dim topViewX As Double
    Dim topViewY As Double
    Dim sideViewX As Double
    Dim sideViewY As Double
    Dim isoViewX As Double
    Dim isoViewY As Double
    Dim viewScale As Double
    
    Set swDrawingDoc = swModel
    Set swSheet = swDrawingDoc.GetCurrentSheet
    vSheetProps = swSheet.GetProperties
    
    'Get sheet dimensions in meters
    sheetWidth = vSheetProps(5)
    sheetHeight = vSheetProps(6)
    
    'Calculate view positions based on sheet size
    'Top view - upper left area
    topViewX = sheetWidth * 0.3
    topViewY = sheetHeight * 0.7
    
    'Front view - below top view (aligned vertically)
    sideViewX = sheetWidth * 0.3
    sideViewY = sheetHeight * 0.35
    
    'Isometric view - upper right corner
    isoViewX = sheetWidth * 0.75
    isoViewY = sheetHeight * 0.7
    
    'Set view scale based on sheet size
    If SheetSizeInput = 4 Then 'A4
        viewScale = 0.4
    ElseIf SheetSizeInput = 3 Then 'A3
        viewScale = 0.5
    ElseIf SheetSizeInput = 2 Then 'A2
        viewScale = 0.75
    ElseIf SheetSizeInput = 1 Then 'A1
        viewScale = 1
    Else
        viewScale = 0.5
    End If
    
    'Get the model from the first drawing view BEFORE deleting
    Dim modelPath As String
    Set swView1 = swDrawingDoc.GetFirstView
    Set swView2 = swView1.GetNextView
    
    If Not swView2 Is Nothing Then
        Set swmod = swView2.ReferencedDocument
        If swmod Is Nothing Then
            MsgBox "Error: Could not get referenced model from the drawing view."
            Exit Sub
        End If
        modelPath = swmod.GetPathName
    Else
        'No model yet, prompt user to insert model first
        MsgBox "Please ensure a model is referenced in the drawing."
        Exit Sub
    End If
    
    'Now delete existing views except the sheet view
    Set swView1 = swDrawingDoc.GetFirstView
    Set swView2 = swView1.GetNextView
    
    Do While Not swView2 Is Nothing
        Dim swNextView As SldWorks.View
        Set swNextView = swView2.GetNextView
        swModel.Extension.SelectByID2 swView2.Name, "DRAWINGVIEW", 0, 0, 0, False, 0, Nothing, 0
        swModel.EditDelete
        Set swView2 = swNextView
    Loop
    
    'Create Top view
    Set swView2 = swDrawingDoc.CreateDrawViewFromModelView3(modelPath, "*Top", topViewX, topViewY, 0)
    If swView2 Is Nothing Then
        MsgBox "Failed to create Top view. Please check if the model contains a standard '*Top' view."
    End If
    If Not swView2 Is Nothing Then
        swView2.ScaleDecimal = viewScale
        swView2.AutoInsertCenterMarks2 7, 11, True, True, True, 0.0025, 0.0025, True, True, 0
    End If
    
    'Create Front view (below top view)
    Set swView3 = swDrawingDoc.CreateDrawViewFromModelView3(modelPath, "*Front", sideViewX, sideViewY, 0)
    If Not swView3 Is Nothing Then
        swView3.ScaleDecimal = viewScale
        swView3.AutoInsertCenterMarks2 7, 11, True, True, True, 0.0025, 0.0025, True, True, 0
    End If
    
    'Create Right side view (lower right, smaller)
    Dim rightViewX As Double
    Dim rightViewY As Double
    rightViewX = sheetWidth * 0.7
    rightViewY = sheetHeight * 0.35
    
    Dim swView5 As SldWorks.View
    Set swView5 = swDrawingDoc.CreateDrawViewFromModelView3(modelPath, "*Right", rightViewX, rightViewY, 0)
    If Not swView5 Is Nothing Then
        swView5.ScaleDecimal = viewScale * 0.5 'Make right view smaller
        swView5.AutoInsertCenterMarks2 7, 11, True, True, True, 0.0025, 0.0025, True, True, 0
    End If
    
    'Create Isometric view (upper right)
    Set swView4 = swDrawingDoc.CreateDrawViewFromModelView3(modelPath, "*Isometric", isoViewX, isoViewY, 0)
    If Not swView4 Is Nothing Then
        swView4.ScaleDecimal = viewScale * 0.5 'Make iso view smaller
        'Set display mode to shaded with edges
        swView4.SetDisplayMode3 False, 6, False, True 'swDisplayMode_ShadedWithEdges = 6
    End If
    
    swModel.GraphicsRedraw2
    
End Sub

' -------------------------------------------------------------------------------------------------------------
    
Sub main()
'This is the main call up section
    FirstTime = 0
    Dim modView As ModelView
    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    swModel.FeatureManager.EnableFeatureTree = False
    Set modView = swModel.ActiveView
    modView.EnableGraphicsUpdate = False
    Set swDraw = swModel
    
    Set swSheet = swDraw.GetCurrentSheet
    vSheetNames = swDraw.GetSheetNames
    bRet = swModel.ActivateSheet(vSheetNames(0))
    
    'Basic error handeling
    Set swview = swDraw.GetFirstView
    str = swview.GetName2
    Set swview = swview.GetNextView
    If swview Is Nothing Then
    
        MsgBox "No model in the drawing view. Please drop a model into the drawing view before using the macro."
        Exit Sub
    End If
    
    SheetProperties
    If SheetSizeInput = "" Then
        MsgBox "Macro terminated as no sheet size requested."
        GoTo EndofCode
    End If
    Seconds1 = Timer()
    
    Copying
    DetermineNameAndType
    CreateViewLayout
    Deleting
    Border
    Tables
    InsertBOMTable
    InsertPicture
    TextBox
    FirstTime = 1 'Timer to use to make subsequent sheets act differently
    SecondarySheets
    
    swModel.ForceRebuild3 True
    swModel.FeatureManager.EnableFeatureTree = True
    modView.EnableGraphicsUpdate = True
    
    'Save the drawing in the same location as the part
    Dim drawingPath As String
    Dim partPath As String
    Dim drawingName As String
    
    partPath = swmod.GetPathName
    If partPath <> "" Then
        'Extract directory and filename without extension
        Dim lastSlash As Integer
        lastSlash = InStrRev(partPath, "\")
        drawingName = Left(partPath, lastSlash) & ModelName & ".SLDDRW"
        
        'Save the drawing
        Dim errors As Long
        Dim warnings As Long
        bRet = swModel.SaveAs3(drawingName, 0, 0)
        
        If bRet Then
            Seconds2 = Timer()
            MsgBox "Sheet format update complete" & vbNewLine & "Time taken: " & Seconds2 - Seconds1 & vbNewLine & vbNewLine & "Drawing saved as:" & vbNewLine & drawingName
        Else
            Seconds2 = Timer()
            MsgBox "Sheet format update complete but failed to save drawing" & vbNewLine & "Time taken: " & Seconds2 - Seconds1
        End If
    Else
        Seconds2 = Timer()
        MsgBox "Sheet format update complete" & vbNewLine & "Time taken: " & Seconds2 - Seconds1 & vbNewLine & vbNewLine & "Could not determine part location - drawing not saved"
    End If
End Sub

' -------------------------------------------------------------------------------------------------------------

Sub SheetProperties()
'This section works out what sheet size is being used and how many sheets there are
    Set swSheet = swDraw.GetCurrentSheet
    vSheetProps = swSheet.GetProperties
    
    'Prompt for sheet size on first sheet only
    If FirstTime = 0 Then
        SheetSizeInput = InputBox("What sheet size do you need?" & vbNewLine & vbNewLine & "Enter:" & vbNewLine & "  4 for A4" & vbNewLine & "  3 for A3" & vbNewLine & "  2 for A2" & vbNewLine & "  1 for A1", "SHEET SIZE REQUIRED")
    End If
    
    If SheetSizeInput = "" Then Exit Sub
    
InputCheck:
            If SheetSizeInput = 4 Then
                'vSheetProps(0) = 6
                bRet = swModel.SetupSheet5(swSheet.GetName, 12, 12, vSheetProps(2), vSheetProps(3), False, "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A4.slddrt", 0.297, 0.21, "Default", True)
            ElseIf SheetSizeInput = 3 Then
                'vSheetProps(0) = 8
                bRet = swModel.SetupSheet5(swSheet.GetName, 12, 12, vSheetProps(2), vSheetProps(3), False, "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A3.slddrt", 0.42, 0.297, "Default", True)
            ElseIf SheetSizeInput = 2 Then
                'vSheetProps(0) = 9
                bRet = swModel.SetupSheet5(swSheet.GetName, 12, 12, vSheetProps(2), vSheetProps(3), False, "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A2.slddrt", 0.594, 0.42, "Default", True)
            ElseIf SheetSizeInput = 1 Then
                'vSheetProps(0) = 10
                bRet = swModel.SetupSheet5(swSheet.GetName, 12, 12, vSheetProps(2), vSheetProps(3), False, "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A1.slddrt", 0.841, 0.594, "Default", True)
            Else
                SheetSizeInput = InputBox("Invalid input! What sheet size do you need?" & vbNewLine & "Input 4 for A4, 3 for A3, 2 for A2 or 1 for A1", "Sheet size request - error in previous", "3")
                If SheetSizeInput = "" Then Exit Sub
                GoTo InputCheck
            End If
            
    ' Get current sheet properties
    Set swSheet = swDraw.GetCurrentSheet
    vSheetProps = swSheet.GetProperties
    vSheetNames = swDraw.GetSheetNames


End Sub

' -------------------------------------------------------------------------------------------------------------

Sub Deleting()
'This section of the code deletes the exisiting custom properties on the sheet as well as any exisiting tables or annotations
    
nNbrProps = swCustPropMgr.Count
lRetVal = swCustPropMgr.GetAll3(vPropNames, vPropTypes, vPropValues, resolved, True)

For j = 0 To nNbrProps - 1
    custPropType = swCustPropMgr.Delete2(vPropNames(j))
Next j

'Select any exisiting tables and delete them to allow update to run
'This is a bit of a hack as it just tries all the combinations of names from 0 to 999
Set swModelDocExt = swModel.Extension

str = "Revision Table"
Status = swModelDocExt.SelectByID2(str, "GENERALTABLEFEAT", 0, 0, 0, False, 0, Nothing, 0)
If (Not (Status = False)) Then
    Set swSelectionMgr = swModel.SelectionManager
    Set swGeneralTableFeature = swSelectionMgr.GetSelectedObject6(1, -1)
    Set swFeature = swGeneralTableFeature.GetFeature
    DeleteOption = swDeleteSelectionOptions_e.swDelete_Absorbed
    Status = swModelDocExt.DeleteSelection2(DeleteOption)
End If
    
For i = 0 To 150
    str = "General Table" & i
    Status = swModelDocExt.SelectByID2(str, "GENERALTABLEFEAT", 0, 0, 0, False, 0, Nothing, 0)
    If (Not (Status = False)) Then
        Set swSelectionMgr = swModel.SelectionManager
        Set swGeneralTableFeature = swSelectionMgr.GetSelectedObject6(1, -1)
        Set swFeature = swGeneralTableFeature.GetFeature
        DeleteOption = swDeleteSelectionOptions_e.swDelete_Absorbed
        Status = swModelDocExt.DeleteSelection2(DeleteOption)
    End If
Next

For i = 0 To 150
    str = "Bill of Materials" & i
    Status = swModelDocExt.SelectByID2(str, "BOMFEATURE", 0, 0, 0, False, 0, Nothing, 0)
    If (Not (Status = False)) Then
        Set swSelectionMgr = swModel.SelectionManager
        Set swBOMFeature = swSelectionMgr.GetSelectedObject6(1, -1)
        Set swFeature = swBOMFeature.GetFeature
        DeleteOption = swDeleteSelectionOptions_e.swDelete_Absorbed
        Status = swModelDocExt.DeleteSelection2(DeleteOption)
    End If
Next

'Select and delete all pictures
swDraw.EditTemplate

Set swSketch = swModel.SketchManager.ActiveSketch
vPics = swSketch.GetSketchPictures

If Not IsEmpty(vPics) Then
        For i = 0 To UBound(vPics)
            Set swSkPic = vPics(i)
            Set swFeat = swSkPic.GetFeature
            swModel.ClearSelection2 True
            swModel.Extension.SelectByID2 swFeat.Name, "SKETCHBITMAP", 0, 0, 0, False, 0, Nothing, 0
            swModel.Extension.DeleteSelection2 swDeleteSelectionOptions_e.swDelete_Absorbed
        Next
End If

For i = 1 To 150
    For j = 1 To UBound(vSheetNames)
        str = "DetailItem" & i & "@Sheet Format" & j
        Status = swModel.Extension.SelectByID2(str, "NOTE", 0.483545891612903, 0.140108810322581, 0, False, 0, Nothing, 0)
        swModel.Extension.DeleteSelection2 swDeleteSelectionOptions_e.swDelete_Absorbed
    Next
Next
    
swDraw.EditSheet

End Sub

' -------------------------------------------------------------------------------------------------------------

Sub Copying()
'This section of the code pulls the custom properties from the model forward into the drawing and gets the tolerance level required
    
Set swSelMgr = swModel.SelectionManager
Set swCustPropMgr = swModel.Extension.CustomPropertyManager("")
Set swview = swDraw.GetFirstView
str = swview.GetName2
Set swview = swview.GetNextView

If swview Is Nothing Then
    MsgBox "No Model in the Drawing view"
    Exit Sub
End If

'str = swview.GetReferencedModelName
Set swmod = swview.ReferencedDocument

'Get configuration name from view
config = swview.ReferencedConfiguration

Propname = swmod.GetCustomInfoNames

'First pass - copy ALL custom properties from model to drawing
j = 1
For m = 0 To UBound(Propname)
    evval = swmod.GetCustomInfoValue(config, Propname(m))
    CustomProperties(j) = evval
    'Delete existing property first to ensure refresh
    swCustPropMgr.Delete2 Propname(m)
    'Add the property with current value
    addstatus = swCustPropMgr.Add2(Propname(m), swCustomInfoText, evval)
    evval = ""
    j = j + 1
Next
        
'Link custom property names to values
'POSSIBLY LEGACY DUE TO CHANGE IN APPROACH
TolTab = 0
Issue = -1
Weight = -1
For i = 0 To UBound(Propname)

    If Propname(i) = "TolTab" Then
        TolTab = i + 1
    ElseIf Propname(i) = "Description" Then
        Description = i + 1
    ElseIf Propname(i) = "Weight" Then
        Weight = i + 1
    ElseIf Propname(i) = "Finish" Then
        Finish = i + 1
    ElseIf Propname(i) = "DrawnBy" Then
        DrawnBy = i + 1
    ElseIf Propname(i) = "Issue" Then
        Issue = i + 1
    ElseIf Propname(i) = "Material" Then
        Material = i + 1
    ElseIf Propname(i) = "MaterialBOM" Then
        Material = i + 1
    ElseIf Propname(i) = "DrawnDate" Then
        DrawnDate = i + 1
    ElseIf Propname(i) = "Watermark" Then
        Watermark = i + 1
    End If

Next

'Determine the required tolerance values
If TolTab > 0 Then
    Location = "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Custom Property Tab\Custom Properties\Tolerance Tables Values\"
    ToleranceList = Location & CustomProperties(TolTab) & ".txt"
    Row_Counter = 0
    Open ToleranceList For Input As #1
        Do Until EOF(1)
            Line Input #1, LineFromFile
            LineItems = Split(LineFromFile, ",")
                For Column_Counter = 0 To 0
                    Tolerance_Data(Row_Counter, Column_Counter) = LineItems(Column_Counter)
                Next
            Row_Counter = Row_Counter + 1
        Loop
    Close #1
End If

'Error if no tolerance table
If TolTab = 0 Then
    MsgBox "No tolerance table has been defined."
    Exit Sub
End If

'Add tolerance custom properties to drawing sheet
swCustPropMgr.Delete2 "ToleranceX"
addstatus = swCustPropMgr.Add2("ToleranceX", swCustomInfoText, "± 1.0")
swCustPropMgr.Delete2 "ToleranceXX"
addstatus = swCustPropMgr.Add2("ToleranceXX", swCustomInfoText, "± 0.25")
swCustPropMgr.Delete2 "ToleranceXXX"
addstatus = swCustPropMgr.Add2("ToleranceXXX", swCustomInfoText, "± 0.13")
swCustPropMgr.Delete2 "ToleranceXXXX"
addstatus = swCustPropMgr.Add2("ToleranceXXXX", swCustomInfoText, "±0.13")
swCustPropMgr.Delete2 "ToleranceAngular"
addstatus = swCustPropMgr.Add2("ToleranceAngular", swCustomInfoText, "1.0")

'Add sheet size property
swCustPropMgr.Delete2 "SheetSize"
If vSheetProps(0) = 8 Then
    addstatus = swCustPropMgr.Add2("SheetSize", swCustomInfoText, "A3")
ElseIf vSheetProps(0) = 9 Then
    addstatus = swCustPropMgr.Add2("SheetSize", swCustomInfoText, "A2")
ElseIf vSheetProps(0) = 10 Then
    addstatus = swCustPropMgr.Add2("SheetSize", swCustomInfoText, "A1")
ElseIf vSheetProps(0) = 6 Then
    addstatus = swCustPropMgr.Add2("SheetSize", swCustomInfoText, "A4")
End If

'Ensure critical properties exist and are refreshed from model
Dim propValue As String

'Material property
swCustPropMgr.Delete2 "Material"
propValue = swmod.CustomInfo2(config, "Material")
If propValue = "" Then propValue = swmod.CustomInfo2("", "Material")
addstatus = swCustPropMgr.Add2("Material", swCustomInfoText, propValue)

'MATERIAL property (uppercase variant)
swCustPropMgr.Delete2 "MATERIAL"
addstatus = swCustPropMgr.Add2("MATERIAL", swCustomInfoText, propValue)

'Weight property
swCustPropMgr.Delete2 "Weight"
propValue = swmod.CustomInfo2(config, "Weight")
If propValue = "" Then propValue = swmod.CustomInfo2("", "Weight")
addstatus = swCustPropMgr.Add2("Weight", swCustomInfoText, propValue)

swCustPropMgr.Delete2 "WEIGHT"
addstatus = swCustPropMgr.Add2("WEIGHT", swCustomInfoText, propValue)

'Description property
swCustPropMgr.Delete2 "Description"
propValue = swmod.CustomInfo2(config, "Description")
If propValue = "" Then propValue = swmod.CustomInfo2("", "Description")
addstatus = swCustPropMgr.Add2("Description", swCustomInfoText, propValue)

'Number property
swCustPropMgr.Delete2 "Number"
propValue = swmod.CustomInfo2(config, "Number")
If propValue = "" Then propValue = swmod.CustomInfo2("", "Number")
addstatus = swCustPropMgr.Add2("Number", swCustomInfoText, propValue)

'Project property
swCustPropMgr.Delete2 "Project"
propValue = swmod.CustomInfo2(config, "Project")
If propValue = "" Then propValue = swmod.CustomInfo2("", "Project")
addstatus = swCustPropMgr.Add2("Project", swCustomInfoText, propValue)

swCustPropMgr.Delete2 "PROJECT"
addstatus = swCustPropMgr.Add2("PROJECT", swCustomInfoText, propValue)

'ProjectName property
swCustPropMgr.Delete2 "ProjectName"
propValue = swmod.CustomInfo2(config, "ProjectName")
If propValue = "" Then propValue = swmod.CustomInfo2("", "ProjectName")
addstatus = swCustPropMgr.Add2("ProjectName", swCustomInfoText, propValue)

'Status property
swCustPropMgr.Delete2 "Status"
propValue = swmod.CustomInfo2(config, "Status")
If propValue = "" Then propValue = swmod.CustomInfo2("", "Status")
addstatus = swCustPropMgr.Add2("Status", swCustomInfoText, propValue)

swCustPropMgr.Delete2 "STATUS"
addstatus = swCustPropMgr.Add2("STATUS", swCustomInfoText, propValue)

'Revision property
swCustPropMgr.Delete2 "Revision"
propValue = swmod.CustomInfo2(config, "Revision")
If propValue = "" Then propValue = swmod.CustomInfo2("", "Revision")
addstatus = swCustPropMgr.Add2("Revision", swCustomInfoText, propValue)

'Cost property
swCustPropMgr.Delete2 "Cost"
propValue = swmod.CustomInfo2(config, "Cost")
If propValue = "" Then propValue = swmod.CustomInfo2("", "Cost")
addstatus = swCustPropMgr.Add2("Cost", swCustomInfoText, propValue)

'Author property
swCustPropMgr.Delete2 "Author"
propValue = swmod.CustomInfo2(config, "Author")
If propValue = "" Then propValue = swmod.CustomInfo2("", "Author")
addstatus = swCustPropMgr.Add2("Author", swCustomInfoText, propValue)

'ProjectManager property
swCustPropMgr.Delete2 "ProjectManager"
propValue = swmod.CustomInfo2(config, "ProjectManager")
If propValue = "" Then propValue = swmod.CustomInfo2("", "ProjectManager")
addstatus = swCustPropMgr.Add2("ProjectManager", swCustomInfoText, propValue)

'ProjectCategory property
swCustPropMgr.Delete2 "ProjectCategory"
propValue = swmod.CustomInfo2(config, "ProjectCategory")
If propValue = "" Then propValue = swmod.CustomInfo2("", "ProjectCategory")
addstatus = swCustPropMgr.Add2("ProjectCategory", swCustomInfoText, propValue)

'DocClass property
swCustPropMgr.Delete2 "DocClass"
propValue = swmod.CustomInfo2(config, "DocClass")
If propValue = "" Then propValue = swmod.CustomInfo2("", "DocClass")
addstatus = swCustPropMgr.Add2("DocClass", swCustomInfoText, propValue)

'PartNumber property
swCustPropMgr.Delete2 "PartNumber"
propValue = swmod.CustomInfo2(config, "PartNumber")
If propValue = "" Then propValue = swmod.CustomInfo2("", "PartNumber")
If propValue = "" Then propValue = ModelName 'Use filename as fallback
addstatus = swCustPropMgr.Add2("PartNumber", swCustomInfoText, propValue)

End Sub

' -------------------------------------------------------------------------------------------------------------

Sub Border()

'Adds blanks template to allow for multiple renewals
bRet = swModel.SetupSheet5(swSheet.GetName, 12, 12, vSheetProps(2), vSheetProps(3), False, "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A3.slddrt", 0.42, 0.297, "Default", True)

'Adds actual template based on sheet size
If vSheetProps(0) = 8 Then
        'Debug.Print "A3"
        bRet = swModel.SetupSheet5(swSheet.GetName, 12, 12, vSheetProps(2), vSheetProps(3), False, "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A3.slddrt", 0.42, 0.297, "Default", True)
    ElseIf vSheetProps(0) = 9 Then
        'Debug.Print "A2"
        bRet = swModel.SetupSheet5(swSheet.GetName, 12, 12, vSheetProps(2), vSheetProps(3), False, "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A2.slddrt", 0.594, 0.42, "Default", True)
    ElseIf vSheetProps(0) = 10 Then
        'Debug.Print "A1"
        bRet = swModel.SetupSheet5(swSheet.GetName, 12, 12, vSheetProps(2), vSheetProps(3), False, "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A1.slddrt", 0.841, 0.594, "Default", True)
    ElseIf vSheetProps(0) = 6 Then
        'Debug.Print "A4"
        bRet = swModel.SetupSheet5(swSheet.GetName, 12, 12, vSheetProps(2), vSheetProps(3), False, "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A4.slddrt", 0.297, 0.21, "Default", True)
    Else
        'Default to A3 if no match
        bRet = swModel.SetupSheet5(swSheet.GetName, 12, 12, vSheetProps(2), vSheetProps(3), False, "C:\NPD\Admin\Templates\SolidWorks PDM Templates\Sheet Formats\Standard - A3.slddrt", 0.42, 0.297, "Default", True)
    End If

End Sub

Sub DetermineNameAndType()
'Gets the type of table that is being discussed

PathName1 = swmod.GetPathName
PathName2 = Right(PathName1, Len(PathName1) - InStrRev(PathName1, "\"))
ModelName = Left(PathName2, (InStr(PathName2, ".") - 1))

If InStrRev(ModelName, "W") = 1 Then
    'Debug.Print "WA"
    DrawType = 1
ElseIf InStrRev(ModelName, "G") = 1 Then
    'Debug.Print "GA"
    DrawType = 2
ElseIf InStrRev(ModelName, "M") = 1 Then
    'Debug.Print "GA"
    DrawType = 4
ElseIf InStrRev(ModelName, "W") = 2 And InStrRev(ModelName, "R") = 1 Then
    DrawType = 5
ElseIf InStrRev(ModelName, "G") = 2 And InStrRev(ModelName, "R") = 1 Then
    DrawType = 6
Else
    'Debug.Print "A"
    DrawType = 3
End If

End Sub

' -------------------------------------------------------------------------------------------------------------

Sub Tables()

 'Creates and formats the tolerance table, title block, revision table, top left block
 BorderLineWeight = 0.25
 GridLineWeight = 0.18

 'Set Table Variables
 ReDim vPickPt(2)
 'Datum point of sheet
 vPickPt(0) = vSheetProps(5) - 0.01
 vPickPt(1) = 0.01 'vSheetProps(6) + 0.01
 vPickPt(2) = 0
 
 Set swDraw = swModel
 vSheetProps = swSheet.GetProperties
 
 'Create Tolerance table
 If TolTab > 0 And DrawType <> 2 And FirstTime = 0 Then
     Set swTable = swDraw.InsertTableAnnotation(vPickPt(0) - 0.12, vPickPt(1), swBOMConfigurationAnchor_BottomRight, 8, 13)
 End If
 
 'Create title block
 Set swTable2 = swDraw.InsertTableAnnotation(vPickPt(0), vPickPt(1), swBOMConfigurationAnchor_BottomRight, 16, 6)
 
 'Create revision table
 'If the sheet is an A3 WA or RWA
 If vSheetProps(0) = 8 And DrawType = 1 And FirstTime = 0 Or vSheetProps(0) = 8 And DrawType = 5 And FirstTime = 0 Then
    Set swTable3 = swDraw.InsertTableAnnotation(0.01, vSheetProps(6) - 0.03, swBOMConfigurationAnchor_TopLeft, 4, 4)
 'If the sheet is A3 but not a WA
 ElseIf vSheetProps(0) = 8 And DrawType <> 1 And FirstTime = 0 Then
    Set swTable3 = swDraw.InsertTableAnnotation(0.01, vSheetProps(6) - 0.02, swBOMConfigurationAnchor_TopLeft, 4, 4)
 'If the sheet is not A3 but is a WA
 ElseIf vSheetProps(0) <> 8 And DrawType = 1 And FirstTime = 0 Then
    Set swTable3 = swDraw.InsertTableAnnotation(0.01, vPickPt(1), swBOMConfigurationAnchor_BottomLeft, 4, 4)
 'If the sheet is not A3 but is not WA
 ElseIf vSheetProps(0) <> 8 And DrawType <> 1 And FirstTime = 0 Then
    Set swTable3 = swDraw.InsertTableAnnotation(0.01, vPickPt(1), swBOMConfigurationAnchor_BottomLeft, 4, 4)
 End If

 
 'Create top left table
 If DrawType = 1 Or DrawType = 5 Then
     Set swTable4 = swDraw.InsertTableAnnotation(0.01, vSheetProps(6) - 0.01, swBOMConfigurationAnchor_TopLeft, 2, 3)
 Else
     Set swTable4 = swDraw.InsertTableAnnotation(0.01, vSheetProps(6) - 0.01, swBOMConfigurationAnchor_TopLeft, 1, 3)
 End If
 
 'Create RGA cyclinder table
 If DrawType = 6 And FirstTime = 0 Then
    Set swTable5 = swDraw.InsertTableAnnotation(vPickPt(0), vPickPt(1) + 0.08, swBOMConfigurationAnchor_BottomRight, 11, 2)
 End If
 
 'Populate tolerance table
 If TolTab > 0 And DrawType <> 2 And FirstTime = 0 Then
     'Formatting Tolerance table
     With swTable
         Value = swTable.MergeCells(0, 0, 0, 12)
         Value = swTable.MergeCells(1, 0, 1, 8)
         Value = swTable.MergeCells(5, 0, 5, 5)
         Value = swTable.MergeCells(4, 7, 4, 12)
         Value = swTable.MergeCells(2, 11, 2, 12)
         Value = swTable.MergeCells(3, 11, 3, 12)
         .SetColumnWidth 0, 0.046, 0
         .SetColumnWidth 1, 0.0117, 0
         .SetColumnWidth 2, 0.0125, 0
         .SetColumnWidth 3, 0.0141, 0
         .SetColumnWidth 4, 0.0157, 0
         .SetColumnWidth 5, 0.0157, 0
         .SetColumnWidth 6, 0.0254, 0
         .SetColumnWidth 7, 0.0188, 0
         .SetColumnWidth 8, 0.0188, 0
         .SetColumnWidth 9, 0.0141, 0
         .SetColumnWidth 10, 0.0157, 0
         .SetColumnWidth 11, 0.0172, 0
         .SetColumnWidth 12, 0.0188, 0
         .SetColumnWidth 13, 0.01775, 0
         .SetColumnWidth 14, 0.01775, 0
         
         For i = 0 To .ColumnCount - 1
             .SetLockColumnWidth i, True
         Next i
         
        'Set the first row to double height to add note
        .SetRowHeight 0, 0.01, 0
        .SetLockRowHeight 0, True
         
         For i = 1 To .RowCount - 1
             .SetRowHeight i, 0.005, 0
             .SetLockRowHeight i, True
         Next i
         
         .GridLineWeight = GridLineWeight
        
         Set swTextFormat = swTable.GetTextFormat
         swTextFormat.CharHeightInPts = 7
         swTextFormat.Bold = False
         swTextFormat.TypeFaceName = "Arial"
         bRet = swTable.SetTextFormat(False, swTextFormat)
        
         .Text(0, 0) = "TOLERANCES TO BE USED UNLESS OTHERWISE STATED" & vbNewLine & "TOLERANCE STANDARD: " & CustomProperties(TolTab)
         Set swTextFormatTitle = swTable.GetCellTextFormat(0, 0)
         swTextFormatTitle.CharHeightInPts = 10
         swTextFormatTitle.Bold = True
         swTextFormatTitle.TypeFaceName = "Arial"
         bRet = swTable.SetCellTextFormat(0, 0, False, swTextFormatTitle)
         
         .Text(1, 0) = "LINEAR DEVIATIONS"
         Set swTextFormatBold = swTable.GetCellTextFormat(1, 0)
         swTextFormatBold.Bold = True
         bRet = swTable.SetCellTextFormat(1, 0, False, swTextFormatBold)
             
         .Text(2, 0) = "DIMENSIONS IN mm"
         bRet = swTable.SetCellTextFormat(2, 0, False, swTextFormatBold)
        
         .Text(4, 0) = "EXTERNAL RADII & CHAMFERS"
         bRet = swTable.SetCellTextFormat(4, 0, False, swTextFormatBold)
             
         .Text(5, 0) = "ANGULAR DEVIATIONS - INTERNAL STANDARD"
         bRet = swTable.SetCellTextFormat(5, 0, False, swTextFormatBold)
        
         .Text(6, 0) = "SHORTER SIDE OF ANGLE mm"
         bRet = swTable.SetCellTextFormat(6, 0, False, swTextFormatBold)
        
         .Text(2, 1) = "0.5<X<3"
         bRet = swTable.SetCellTextFormat(2, 1, False, swTextFormatBold)
         .Text(2, 2) = "3<X<6"
         bRet = swTable.SetCellTextFormat(2, 2, False, swTextFormatBold)
         .Text(2, 3) = "6<X<30"
         bRet = swTable.SetCellTextFormat(2, 3, False, swTextFormatBold)
         .Text(2, 4) = "30<X<120"
         bRet = swTable.SetCellTextFormat(2, 4, False, swTextFormatBold)
         .Text(2, 5) = "120<X<400"
         bRet = swTable.SetCellTextFormat(2, 5, False, swTextFormatBold)
         .Text(2, 6) = "400<X<1000"
         bRet = swTable.SetCellTextFormat(2, 6, False, swTextFormatBold)
         .Text(2, 7) = "1000<X<2000"
         bRet = swTable.SetCellTextFormat(2, 7, False, swTextFormatBold)
         .Text(2, 8) = "2000<X<4000"
         bRet = swTable.SetCellTextFormat(2, 8, False, swTextFormatBold)
         .Text(2, 11) = "CIRCULAR RUN-OUT"
         bRet = swTable.SetCellTextFormat(2, 11, False, swTextFormatBold)
        
         .Text(3, 1) = "±" & Tolerance_Data(1, 0)
         .Text(3, 2) = "±" & Tolerance_Data(2, 0)
         .Text(3, 3) = "±" & Tolerance_Data(3, 0)
         .Text(3, 4) = "±" & Tolerance_Data(4, 0)
         .Text(3, 5) = "±" & Tolerance_Data(5, 0)
         .Text(3, 6) = "±" & Tolerance_Data(6, 0)
         .Text(3, 7) = "±" & Tolerance_Data(7, 0)
         .Text(3, 8) = "±" & Tolerance_Data(8, 0)
         .Text(3, 11) = "±" & Tolerance_Data(10, 0)
        
         .Text(4, 1) = "±" & Tolerance_Data(12, 0)
         .Text(4, 2) = "±" & Tolerance_Data(13, 0)
         .Text(4, 3) = "±" & Tolerance_Data(14, 0)
         .Text(4, 7) = "GEOMETRIC TOLERANCE DEVIATIONS"
         bRet = swTable.SetCellTextFormat(4, 7, False, swTextFormatBold)
        
         .Text(5, 7) = "X<10"
         bRet = swTable.SetCellTextFormat(5, 7, False, swTextFormatBold)
         .Text(5, 8) = "10<X<30"
         bRet = swTable.SetCellTextFormat(5, 8, False, swTextFormatBold)
         .Text(5, 9) = "30<X<100"
         bRet = swTable.SetCellTextFormat(5, 9, False, swTextFormatBold)
         .Text(5, 10) = "100<X<300"
         bRet = swTable.SetCellTextFormat(5, 10, False, swTextFormatBold)
         .Text(5, 11) = "300<X<1000"
         bRet = swTable.SetCellTextFormat(5, 11, False, swTextFormatBold)
         .Text(5, 12) = "1000<X<3000"
         bRet = swTable.SetCellTextFormat(5, 12, False, swTextFormatBold)
        
         .Text(6, 1) = "X<10"
         bRet = swTable.SetCellTextFormat(6, 1, False, swTextFormatBold)
         .Text(6, 2) = "10<X<50"
         bRet = swTable.SetCellTextFormat(6, 2, False, swTextFormatBold)
         .Text(6, 3) = "50<X<120"
         bRet = swTable.SetCellTextFormat(6, 3, False, swTextFormatBold)
         .Text(6, 4) = "120<X<400"
         bRet = swTable.SetCellTextFormat(6, 4, False, swTextFormatBold)
         .Text(6, 5) = "400<X"
         bRet = swTable.SetCellTextFormat(6, 5, False, swTextFormatBold)
         .Text(6, 6) = "STRAIGHT/FLAT"
         bRet = swTable.SetCellTextFormat(6, 6, False, swTextFormatBold)
         .Text(6, 7) = "±" & Tolerance_Data(16, 0)
         .Text(6, 8) = "±" & Tolerance_Data(17, 0)
         .Text(6, 9) = "±" & Tolerance_Data(18, 0)
         .Text(6, 10) = "±" & Tolerance_Data(19, 0)
         .Text(6, 11) = "±" & Tolerance_Data(20, 0)
         .Text(6, 12) = "±" & Tolerance_Data(21, 0)
        
         .Text(7, 1) = "±" & Tolerance_Data(23, 0) & "°"
         .Text(7, 2) = "±" & Tolerance_Data(24, 0) & "°"
         .Text(7, 3) = "±" & Tolerance_Data(25, 0) & "°"
         .Text(7, 4) = "±" & Tolerance_Data(26, 0) & "°"
         .Text(7, 5) = "±" & Tolerance_Data(27, 0) & "°"
         .Text(7, 6) = "PERPENDICULAR"
         bRet = swTable.SetCellTextFormat(7, 6, False, swTextFormatBold)
         .Text(7, 7) = "±" & Tolerance_Data(29, 0)
         .Text(7, 8) = "±" & Tolerance_Data(30, 0)
         .Text(7, 9) = "±" & Tolerance_Data(31, 0)
         .Text(7, 10) = "±" & Tolerance_Data(32, 0)
         .Text(7, 11) = "±" & Tolerance_Data(33, 0)
         .Text(7, 12) = "±" & Tolerance_Data(34, 0)
 
     End With
 End If
 
 'Values to adapt Title box table
 With swTable2
     'Top left square
     Value = swTable2.MergeCells(0, 0, 5, 1)
     'Bottom right square
     Value = swTable2.MergeCells(8, 3, 14, 5)
     '"Drawing is the property..." square
     Value = swTable2.MergeCells(5, 3, 7, 5)
     'Title square
     Value = swTable2.MergeCells(6, 0, 10, 2)
     'Drawing number square
     Value = swTable2.MergeCells(11, 0, 12, 2)
     'Material square
     Value = swTable2.MergeCells(13, 0, 13, 2)
     'Finish square
     Value = swTable2.MergeCells(14, 0, 14, 2)
     'Weight square
     Value = swTable2.MergeCells(15, 0, 15, 2)
     'Revision square
     Value = swTable2.MergeCells(15, 0, 15, 2)
     'Sheet size square
     Value = swTable2.MergeCells(4, 2, 5, 2)
     
     Set swTextFormat = swTable2.GetTextFormat
     swTextFormat.CharHeightInPts = 7
     swTextFormat.Bold = False
     bRet = swTable2.SetTextFormat(False, swTextFormat)
     
     'Text for top part of tabel
     .Text(0, 0) = ""
     bRet = swTable2.SetCellTextFormat(0, 0, False, swTextFormatBold)
     .Text(0, 2) = "APPV'D"
     bRet = swTable2.SetCellTextFormat(0, 2, False, swTextFormatBold)
     .Text(1, 2) = "MAN CHK'D"
     bRet = swTable2.SetCellTextFormat(1, 2, False, swTextFormatBold)
     .Text(2, 2) = "DES CHK'D"
     bRet = swTable2.SetCellTextFormat(2, 2, False, swTextFormatBold)
     .Text(3, 2) = "DRAWN"
     bRet = swTable2.SetCellTextFormat(3, 2, False, swTextFormatBold)
     .Text(4, 3) = "NAME"
     bRet = swTable2.SetCellTextFormat(4, 3, False, swTextFormatBold)
     .Text(4, 4) = "SIGNATURE"
     bRet = swTable2.SetCellTextFormat(4, 4, False, swTextFormatBold)
     .Text(4, 5) = "DATE"
     bRet = swTable2.SetCellTextFormat(4, 5, False, swTextFormatBold)
     .Text(5, 3) = "THIS DRAWING IS THE PROPERTY OF JOSEPH JOSEPH LTD AND MUST NOT BE COPIED OR REPRODUCED WITHOUT WRITTEN CONSENT"
     bRet = swTable2.SetCellTextFormat(5, 3, False, swTextFormatBold)
     .Text(6, 0) = "$PRPSHEET:" + Chr(34) + "Description" + Chr(34)
     Set swTextFormatTitleBlock = swTable2.GetCellTextFormat(6, 0)
     swTextFormatTitleBlock.CharHeightInPts = 14
     swTextFormatTitleBlock.Bold = True
     swTextFormatTitleBlock.TypeFaceName = "Arial"
     bRet = swTable2.SetCellTextFormat(6, 0, False, swTextFormatTitleBlock)
     .Text(11, 0) = "DWG NO. " + "$PRPSHEET:" + Chr(34) + "SW-File Name" + Chr(34) '& ModelName
     Set swTextFormatDWGNo = swTable2.GetCellTextFormat(11, 0)
     swTextFormatDWGNo.CharHeightInPts = 12
     swTextFormatDWGNo.Bold = True
     swTextFormatDWGNo.TypeFaceName = "Arial"
     bRet = swTable2.SetCellTextFormat(11, 0, False, swTextFormatDWGNo)
     .Text(13, 0) = "MATERIAL: " + "$PRPSHEET:" + Chr(34) + "MATERIAL" + Chr(34) '"MATERIAL: " & CustomProperties(Material)
     .CellTextHorizontalJustification(13, 0) = 1
     .Text(14, 0) = "FINISH: " + "$PRPSHEET:" + Chr(34) + "FINISH" + Chr(34) '& CustomProperties(Finish)
     .CellTextHorizontalJustification(14, 0) = 1
     'If Weight > 0 Then
         .Text(15, 0) = "WEIGHT: " + "$PRPSHEET:" + Chr(34) + "WEIGHT" + Chr(34) + " kg" '& CustomProperties(Weight) & " kg"
         .CellTextHorizontalJustification(15, 0) = 1
     'ElseIf Weight < 0 Then
         '.Text(15, 0) = "WEIGHT: N/A"
         '.CellTextHorizontalJustification(15, 0) = 1
     'End If
     'If Issue >= 0 Then
         'If Len(CustomProperties(Issue)) > 0 Then
             .Text(15, 3) = "REVISION: " + "$PRPSHEET:" + Chr(34) + "ISSUE" + Chr(34) ' & CustomProperties(Issue)
         'Else
             '.Text(15, 3) = "REVISION: -"
         'End If
     'Else
         '.Text(15, 3) = "REVISION: -"
     'End If
     .Text(0, 3) = "$PRPSHEET:" + Chr(34) + "APPROVEDBY" + Chr(34)   'CustomProperties(ApprovedBy)
     .Text(0, 5) = "$PRPSHEET:" + Chr(34) + "APPROVEDDATE" + Chr(34)   'CustomProperties(ApprovedDate)
     .Text(2, 3) = "$PRPSHEET:" + Chr(34) + "CHECKED BY" + Chr(34)   'CustomProperties(CheckedBy)
     .Text(2, 5) = "$PRPSHEET:" + Chr(34) + "CHECKEDDATE" + Chr(34)    'CustomProperties(CheckedDate)
     .Text(3, 3) = "$PRPSHEET:" + Chr(34) + "DRAWNBY" + Chr(34)    'CustomProperties(DrawnBy)
     .Text(3, 5) = "$PRPSHEET:" + Chr(34) + "DRAWNDATE" + Chr(34)    'CustomProperties(DrawnDate)
     If vSheetProps(0) = 8 Then
         .Text(4, 2) = "A3"
     ElseIf vSheetProps(0) = 9 Then
         .Text(4, 2) = "A2"
     ElseIf vSheetProps(0) = 10 Then
         .Text(4, 2) = "A1"
     End If
     Set swTextFormatSheetSize = swTable2.GetCellTextFormat(4, 2)
     swTextFormatSheetSize.CharHeightInPts = 14
     swTextFormatSheetSize.Bold = True
     swTextFormatSheetSize.TypeFaceName = "Arial"
     bRet = swTable2.SetCellTextFormat(4, 2, False, swTextFormatSheetSize)
     .Text(15, 4) = "SCALE: " + "$PRP:" + Chr(34) + "SW-Sheet Scale" + Chr(34) '& vSheetProps(2) & ":" & vSheetProps(3)
     .Text(15, 5) = "SHEET " + "$PRP:" + Chr(34) + "SW-Current Sheet" + Chr(34) + " OF " + "$PRP:" + Chr(34) + "SW-Total Sheets" + Chr(34)  '& vSheetProps(2) & " OF " & p 'THIS NEEDS SORTING
         
         
     For i = 0 To .RowCount - 1
         .SetRowHeight i, 0.005, 0
         .SetLockRowHeight i, True
     Next i
     .GridLineWeight = GridLineWeight
    
     .SetColumnWidth 0, 0.02, 0
     .SetColumnWidth 1, 0.02, 0
     .SetColumnWidth 2, 0.02, 0
     .SetColumnWidth 3, 0.02, 0
     .SetColumnWidth 4, 0.02, 0
     .SetColumnWidth 5, 0.02, 0
     For i = 0 To .ColumnCount - 1
         .SetLockColumnWidth i, True
     Next i
     
 End With
     
'Values to adapt Revision table
 With swTable3
    'Revisions title
    Value = swTable3.MergeCells(0, 0, 0, 3)
    'Additional note
    Value = swTable3.MergeCells(3, 0, 3, 3)
 
    .SetColumnWidth 0, 0.02, 0
    .SetColumnWidth 1, 0.06, 0
    .SetColumnWidth 2, 0.02, 0
    .SetColumnWidth 3, 0.02, 0
    
    For i = 0 To .ColumnCount - 1
        .SetLockColumnWidth i, True
    Next i
 
    For i = 0 To .RowCount - 1
        .SetRowHeight i, 0.005, 0
        .SetLockRowHeight i, True
    Next i
    .GridLineWeight = GridLineWeight
    
    Set swTextFormat = swTable3.GetTextFormat
    swTextFormat.CharHeightInPts = 7
    swTextFormat.Bold = False
    bRet = swTable3.SetTextFormat(False, swTextFormat)
 
    
    .Text(0, 0) = "REVISIONS"
    bRet = swTable3.SetCellTextFormat(0, 0, False, swTextFormatTitle)
    .Text(1, 0) = "ISSUE"
    Set swTextFormatLeftJust = swTable3.GetCellTextFormat(1, 0)
    swTextFormatLeftJust.Bold = True
    .Text(2, 0) = "$PRPSHEET:" + Chr(34) + "Rev-01" + Chr(34)
    bRet = swTable3.SetCellTextFormat(1, 0, False, swTextFormatLeftJust)
    .Text(1, 1) = "DESCRIPTION"
    bRet = swTable3.SetCellTextFormat(1, 1, False, swTextFormatLeftJust)
    .Text(2, 1) = "$PRPSHEET:" + Chr(34) + "Description-01" + Chr(34)
    .Text(1, 2) = "DATE "
    bRet = swTable3.SetCellTextFormat(1, 2, False, swTextFormatLeftJust)
    .Text(2, 2) = "$PRPSHEET:" + Chr(34) + "Date modified-01" + Chr(34)
    .Text(1, 3) = "MODIFIED BY"
    bRet = swTable3.SetCellTextFormat(1, 3, False, swTextFormatLeftJust)
    .Text(2, 3) = "$PRPSHEET:" + Chr(34) + "Modified by-01" + Chr(34)
    .Text(3, 0) = "THE FULL REVISION HISTORY CAN BE FOUND IN THE PDM RECORDS"
    bRet = swTable3.SetCellTextFormat(1, 3, False, swTextFormatLeftJust)
 
End With

' Top left table
With swTable4
 
    Value = swTable4.MergeCells(1, 0, 1, 2)
 
    .SetColumnWidth 0, 0.065, 0
    .SetColumnWidth 1, 0.065, 0
    .SetColumnWidth 2, 0.05, 0
 
    For i = 0 To .ColumnCount - 1
        .SetLockColumnWidth i, True
    Next i
 
    For i = 0 To .RowCount - 1
        .SetRowHeight i, 0.01, 0
        .SetLockRowHeight i, True
    Next i
    .GridLineWeight = GridLineWeight
    
    Set swTextFormat = swTable4.GetTextFormat
    swTextFormat.CharHeightInPts = 10
    swTextFormat.Bold = True
    swTextFormat.TypeFaceName = "Arial"
    bRet = swTable4.SetTextFormat(False, swTextFormat)

    .Text(0, 0) = "DWG NO. " + "$PRPSHEET:" + Chr(34) + "SW-File Name" + Chr(34) ' & ModelName
    Set swTextFormat = swTable4.GetCellTextFormat(0, 0)
    swTextFormat.CharHeightInPts = 14
    swTextFormat.Bold = True
    swTextFormat.TypeFaceName = "Arial"
    bRet = swTable4.SetCellTextFormat(0, 0, False, swTextFormat)
    .Text(0, 1) = "DO NOT SCALE, IF IN DOUBT ASK! DESTROY DRAWING AFTER USE"
    .Text(0, 2) = "THIRD ANGLE"
    .CellTextHorizontalJustification(0, 2) = 1
    
    If DrawType = 1 Then ' WA
        Set swTextFormat = swTable4.GetCellTextFormat(1, 0)
        swTextFormat.CharHeightInPts = 12
        bRet = swTable4.SetCellTextFormat(1, 0, False, swTextFormat)
        .Text(1, 0) = "ALL WELDS IN ACCORDANCE WITH BS EN 15085, TO A MINIMUM WELD PERFORMANCE CLASS OF CP D UNLESS OTHERWISE STATED"
    ElseIf DrawType = 5 Then ' RWA
        Set swTextFormat = swTable4.GetCellTextFormat(1, 0)
        swTextFormat.CharHeightInPts = 12
        bRet = swTable4.SetCellTextFormat(1, 0, False, swTextFormat)
        .Text(1, 0) = "WELDS TO ACHIEVE A MINIMUM QUALITY LEVEL C AS SPECIFIED IN BS EN ISO 5817 UNLESS OTHERWISE STATED"
    End If
End With
          

Sub InsertBOMTable()
'Section generates the BOm based on an exisiting template

If Not DrawType = 3 Then
    Set swModelDocExt = swModel.Extension
    For i = 1 To 50
        str = "Drawing View" & i
        Status = swDraw.ActivateView(str)
        If Status = True Then
            Exit For
        End If
    Next i
        
    Set swview = swDraw.ActiveDrawingView
    ' Insert parts-only BOM table
    AnchorType = swBOMConfigurationAnchor_TopRight
    BomType = 2 ' 1 = PartsOnly 2 = TopLevelOnly 3 = Indented
    TableTemplate = "C:\NPD\Admin\Templates\SolidWorks PDM Templates\SLD JJ - BOM ASSY TABLE.sldbomtbt"
    Configuration = swview.ReferencedConfiguration
    Set swBOMAnnotation = swview.InsertBomTable4(False, vSheetProps(5) - 0.01, vSheetProps(6) - 0.01, AnchorType, BomType, Configuration, TableTemplate, False, swNumberingType_Detailed, True)
    Set swBOMFeature = swBOMAnnotation.BomFeature
    swDraw.ForceRebuild
    
End If

End Sub

' --------------------------------------------------------------------------------

Sub InsertPicture()
'Section inserts the logo and third angle symbol

swDraw.EditTemplate
Set SkPicture = swDraw.SketchManager.InsertSketchPicture("C:\NPD\Admin\Templates\SolidWorks PDM Templates\Images\Joseph_Joseph_Logo.png")
swDraw.EditSheet
SkPicture.SetSize 0.06, 0.03, True
SkPicture.SetOrigin vSheetProps(5) - 0.07, 0.0175
bRet = SkPicture.SetTransparency(1, 1, 2, 0)

swModel.ClearSelection

swDraw.EditTemplate
Set SkPicture2 = swDraw.SketchManager.InsertSketchPicture("C:\NPD\Admin\Templates\SolidWorks PDM Templates\Images\Third_angle_projection_symbol.png")
swDraw.EditSheet
SkPicture2.SetSize 0.02, 0.0078, True
SkPicture2.SetOrigin 0.1675, vSheetProps(6) - 0.019
bRet = SkPicture2.SetTransparency(3, 1, 16777215, 0)
swModel.ClearSelection

End Sub

'------------------------------------------------------------------------------------------------------


Sub SecondarySheets()
    If Not DrawType = 3 Then
        Set swApp = Application.SldWorks
        Set swModel = swApp.ActiveDoc
        Set swDraw = swModel
        Set swSheet = swDraw.GetCurrentSheet
        vSheetNames = swDraw.GetSheetNames
        For i = 1 To UBound(vSheetNames)
            'Debug.Print "  SheetName[" & i & "] = " & vSheetNames(i)
            bRet = swModel.ActivateSheet(vSheetNames(i))
            SheetProperties
            Border
            'Deleting
            'Copying
            Tables
            InsertPicture
            TextBox
        Next i
    
        bRet = swModel.ActivateSheet(vSheetNames(0))
        
    End If
End Sub

Sub Easy_A_Drawing()

'Set up Solidworks
Set swApp = Application.SldWorks
'Get active document
Set swModel = swApp.ActiveDoc
ModelPath = swModel.GetPathName

'Find the plane with the sketch in


'Open drawing for part
'Currently assumes A3
Dim swSheetWidth As Double
swSheetWidth = 0.42
Dim swSheetHeight As Double
swSheetHeight = 0.297
Set Part = swApp.NewDocument("C:\NPD\Admin\Templates\SolidWorks PDM Templates\Standard - A3.DRWDOT", 12, swSheetWidth, swSheetHeight)

'Get the principle plane
PrinciplePlane = InputBox("What is the main plane the profile is drawn in?" & vbNewLine & vbNewLine & "Front plane = F" & vbNewLine & "Top plane = T" & vbNewLine & "Right plane = R", "Principle Plane")

If PrinciplePlane = "F" Or PrinciplePlane = "f" Then
    MainPlane = "*Front"
ElseIf PrinciplePlane = "T" Or PrinciplePlane = "t" Then
    MainPlane = "*Top"
ElseIf PrinciplePlane = "R" Or PrinciplePlane = "r" Then
    MainPlane = "*Right"
End If

'Import drawing
Part.GraphicsRedraw2
Dim myView As Object
Set myView = Part.CreateDrawViewFromModelView3(ModelPath, MainPlane, (1.5 * swSheetWidth) / 4, swSheetHeight / 2, 0)
boolstatus = myView.AutoInsertCenterMarks2(7, 11, True, True, True, 0.0025, 0.0025, True, True, 0)
boolstatus = myView.SetDisplayMode3(False, 1, False, True)
'boolstatus = Part.Extension.SelectByID2("Drawing View11", "DRAWINGVIEW", 0, 0, 0, False, 0, Nothing, 0)
'boolstatus = Part.ActivateView("Drawing View11")
Set myView = Part.CreateUnfoldedViewAt3((3 * swSheetWidth) / 4, swSheetHeight / 2, 0, False)


'Dimension the drawing
Dim vAnnotations As Variant
vAnnotations = Part.InsertModelAnnotations3(0, 1212424, True, True, False, False)
'vAnnotations = Part.InsertModelAnnotations3(0, 32768, True, True, False, False)
'vAnnotations = Part.InsertModelAnnotations3(0, 1048576, True, True, False, True)



'Open new sheet and add DXF file
bRet = Part.ActivateSheet("Sheet2")
Set myView = Part.CreateDrawViewFromModelView3(ModelPath, MainPlane, swSheetWidth / 2, swSheetHeight / 2, 0)

'Return to first sheet
bRet = Part.ActivateSheet("Sheet1")

    'Add a new note to the sheet format template
    Dim swNote As Note
    'Set Part = swApp.ActiveDoc
    Set swNote = Part.InsertNote("THIS DRAWING HAS BEEN AUTOMATICALLY GENERATED")
    Dim swAnno As Annotation
    Set swAnno = swNote.GetAnnotation
    swAnno.SetPosition2 0.016, 0.285, 0
    Dim txtFormat As TextFormat
    Set txtFormat = swAnno.GetTextFormat(0)
    txtFormat.BackWards = (txtFormat.BackWards = False)
    txtFormat.Bold = True
    txtFormat.CharHeightInPts = 1 * txtFormat.CharHeightInPts
    swAnno.SetTextFormat 0, False, txtFormat

bRet = Part.ForceRebuild3(False)

End Sub

